# Generated by Django 5.1.3 on 2024-12-02 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostLike',
        ),
    ]
