# Generated by Django 5.1.3 on 2024-11-17 08:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3, 'The name of the landmark must be logger than 2 symbols')])),
                ('location_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3, 'The location name must be logger than 2 symbols')])),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='landmarks/')),
                ('map_location', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landmarks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalLandmarkInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_transition', models.BooleanField(default=False)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('is_accessible', models.BooleanField(default=False)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('suitable_for_children', models.BooleanField(default=False)),
                ('has_eating_places', models.BooleanField(default=False)),
                ('is_ennobled', models.BooleanField(default=False)),
                ('start_point', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(3, 'The start point must be logger than 2 symbols')])),
                ('end_point', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(3, 'The end point must be logger than 2 symbols')])),
                ('accessible_by_car', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('landmark', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional_landmark_info', to='landmark.landmark')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('landmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='landmark.landmark')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('landmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='landmark.landmark')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'landmark')},
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('landmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='landmark.landmark')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'landmark')},
            },
        ),
    ]
