# Generated by Django 5.1.3 on 2024-11-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmark',
            name='map_location',
            field=models.TextField(),
        ),
    ]
