# Generated by Django 5.1.3 on 2024-12-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0002_alter_landmark_map_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmark',
            name='level',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard'), ('Extra Hard', 'Extra Hard')], default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='landmark',
            name='image',
            field=models.ImageField(upload_to='landmarks/'),
        ),
    ]
