# Generated by Django 5.1.3 on 2024-12-02 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_postlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlike',
            name='to_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='post.post'),
        ),
    ]
