# Generated by Django 5.1.3 on 2024-11-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('landmark', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='background_image',
            field=models.ImageField(default='images/default_background.jpg', upload_to='background_images/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='landmarks_visited',
            field=models.ManyToManyField(blank=True, null=True, related_name='visited_by_profiles', to='landmark.landmark'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Professional', 'Professional'), ('Expert', 'Expert')], default='Beginner', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/anonymous_full.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
