# Generated by Django 5.1.3 on 2024-11-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_background_image_profile_landmarks_visited_and_more'),
        ('landmark', '0002_alter_landmark_map_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='landmarks_visited',
            field=models.ManyToManyField(blank=True, related_name='visited_by_profiles', to='landmark.landmark'),
        ),
    ]
