# Generated by Django 5.1.3 on 2024-12-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_background_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Professional', 'Professional'), ('Expert', 'Expert')], default='Beginner', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='points',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
